### ISSUE TITLE
Composability with cssify

### ISSUE THREAD

**Issue by faergeek** [asbjornenge/stylusify#2]
What about supporting usage like this?

```
browserify --transform stylusify --transform cssify bundle.js
```

`cssify` supports injecting styles in browser and will support writing to disk and css modules soon.

All you need is instead of doing this:

``` javascript
return done(null, 'module.exports="'+esc(css)+'"')
```

Do this:

``` javascript
return done(null, css)
```

i.e. output plain css without wrapping through option or as a default behavior (`cssify` supports just wrapping css as a module too).

I can provide a real example of usage (a repo) a bit later.

**Comment by asbjornenge** [comment]
@faergeek sure, I'll be open to do that as an option :smile: How would `cssify` pick up on the stylus module? Isn't it due to a filename and not the content that transforms like this find their modules/files? I'm curious to see an example :+1:

**Comment by faergeek** [comment]
If you don't care that you can't actually run it yet, I provided example of usage here
https://gist.github.com/substack/68f8d502be42d5cd4942#gistcomment-1615377

**Comment by asbjornenge** [comment]
@faergeek Ok, so you are trying to make a convention for these css type plugins so that they can be used together? That sounds good to me :smile: :+1: Just as long as they can still be used standalone and that is the default, I'm on board. We could add a `--cssify` flag which would make the transform "align" with this convention.

I'm no browserify expert, but I'm fairly sure you would need something like in your last example with the `extractify` plugin to make the transforms composeable. Otherwise you would need to "tag" / prefix the generated output somehow!?

**Comment by faergeek** [comment]
About flag, I think something like `--raw` or `--no-wrap` would work better :+1: 

Just to clarify, `extractify` plugin which exists right now does not do what I mean.
Probably it should be called `splittify` or something like that, it's purpose is to `split` matching modules into another pipeline and extract it into a separate bundle.
I probably should look into how existing partitioning solutions work and see if they can be used for that.

I still don't know how to implement something like that right now.
I'm not browserify expert either :-)

**Comment by asbjornenge** [comment]
@faergeek :+1: keep me posted :smiley_cat:
